from django.conf.urls import patterns, include, url
from appointment_detail import *
from tests import *
import method


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'homemaking.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', index),
    url(r'^login_in$', login_in),
    url(r'^register$', register),
    url(r'^forget_password$', forget_password),
    url(r'^operate_new$', operate_new),
    url(r'^operate_get$', operate_get),
    url(r'^operate_finish$', operate_finish),
    url(r'^operate_cancel$', operate_cancel),
    url(r'^operate_appraise$', operate_appraise),
    url(r'^find_appointment$', find_appointment),
    url(r'^user_mes$', user_mes),
    url(r'^notice$', notice),
    url(r'^program_manage$', program_manage),
    url(r'^program_manage_two$', program_manage_two),
    url(r'^advertisement_manage$', advertisement_manage),
    url(r'^push_message$', push_message),
    url(r'^goods_manage$', goods_manage),
    url(r'^coupon_manage$', coupon_manage),
    url(r'^game_manage$', game_manage),
    url(r'^vip_manage$', vip_manage),
    url(r'^give_coupon$', give_coupon),
    url(r'^check_coupon$', check_coupon),
    url(r'^set_coupon$', set_coupon),
    url(r'^feed_back$', feed_back),
    url(r'^set_game$', set_game),
    url(r'^check_game_record$', game_record),
    url(r'^advertisement_edit$', advertisement_edit),
    #option
    url(r'^register_verify$', phone_verify),
    url(r'^f_register_verify$', f_phone_verify),
    url(r'^get_new_appointment$', get_new_appointment),
    url(r'^get_new_appointment_count$', get_new_appointment_count),
    url(r'^appointment_get$', get_appointment),
    url(r'^appointment_cancel_n$', cancel_appointment_n),
    url(r'^appointment_cancel_g$', cancel_appointment_g),
    url(r'^appointment_finish$', finish_appointment),
    url(r'^appointment_info_add$', appointment_add_info),
    url(r'^appointment_get_all$', get_appointment_all),
    url(r'^appointment_cancel_all_n$', cancel_appointment_all_n),
    url(r'^appointment_cancel_all_g$', cancel_appointment_all_g),
    url(r'^appointment_finish_all$', finish_appointment_all),
    url(r'^change_password$', change_password),
    url(r'^change_area$', change_area),
    url(r'^out_appointment$', out_appointment),
    url(r'^delete_program_detail$', delete_program_detail),
    url(r'^edit_program_detail$', edit_program_detail),
    url(r'^edit_program_p_detail$', edit_program_p_detail),
    url(r'^delete_program_p$', delete_program_p),
    url(r'^delete_advertisement$', delete_advertisement),
    url(r'^edit_goods_p$', edit_goods_p),
    url(r'^delete_goods_p_ad$', delete_goods_p_ad),
    url(r'^edit_goods_o$', edit_goods_o),
    url(r'^edit_goods$', edit_goods),
    url(r'^delete_goods$', delete_goods),
    url(r'^get_item_mes$', method.get_item_mes),
    url(r'^check_home_item_sort_id', check_home_item_sort_id),
    url(r'^check_home_item_p_sort_id', check_home_item_p_sort_id),
    # test
    url(r'^create_coupons$', create_coupons),
    url(r'^create_appointments$', create_appointments),
    url(r'^create_feed_backs$', create_feed_backs),
    url(r'^create_vips$', create_vips),
    url(r'^create_appointments_appraise$', create_appointments_appraise),
)