from django.conf.urls import patterns, include, url
from appointment_detail import *


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'homemaking.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', index),
    url('^login_in$', login_in),
    url('^register$', register),
    url('^forget_password$', forget_password),
    url('^operate_new$', operate_new),
    url('^operate_get$', operate_get),
    url('^operate_finish$', operate_finish),
    url('^operate_cancel$', operate_cancel),
    url('^find_appointment$', find_appointment),
    url('^user_mes$', user_mes),
    url('^notice$', notice),
    url('^program_manage$', program_manage),
    url('^advertisement_manage$', advertisement_manage),
    url('^push_message$', push_message),
    url('^goods_manage$', goods_manage),
    url('^coupon_manage$', coupon_manage),
    url('^game_manage$', game_manage),
    url('^vip_manage$', vip_manage),
    url('^add_goods_p$', add_goods_p),
    #option
    url('^register_verify$', phone_verify),
    url('^f_register_verify$', f_phone_verify),
    url('^get_new_appointment$', get_new_appointment),
    url('^get_new_appointment_count$', get_new_appointment_count),
    url('^appointment_get$', get_appointment),
    url('^appointment_cancel_n$', cancel_appointment_n),
    url('^appointment_cancel_g$', cancel_appointment_g),
    url('^appointment_finish$', finish_appointment),
    url(r'^appointment_info_add$', appointment_add_info),
    url('^appointment_get_all$', get_appointment_all),
    url('^appointment_cancel_all_n$', cancel_appointment_all_n),
    url('^appointment_cancel_all_g$', cancel_appointment_all_g),
    url('^appointment_finish_all$', finish_appointment_all),
    url('^change_password$', change_password),
    url('^change_area$', change_area),
    url('^out_appointment$', out_appointment),
    url('^delete_program_detail$', delete_program_detail),
    url('^edit_program_detail$', edit_program_detail),
    url('^edit_program_p_detail$', edit_program_p_detail),
    url('^delete_program_p$', delete_program_p),
    url('^delete_advertisement$', delete_advertisement),
)